In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

import numpy as np

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

# Logistic Regression

In [4]:
logReg = cross_val_score(LogisticRegression(solver='newton-cg', max_iter=1000), iris.data, iris.target, cv=3)
print(logReg)
print(np.average(logReg))

[0.98 0.96 0.98]
0.9733333333333333


# Support Vector Machines

In [5]:
svm = cross_val_score(SVC(), iris.data, iris.target, cv=3)
print(svm)
print(np.average(svm))

[0.96 0.98 0.94]
0.96


# Random Forest

In [6]:
rf = cross_val_score(RandomForestClassifier(n_estimators=100), iris.data, iris.target, cv=3)
print(rf)
print(np.average(rf))

[0.98 0.94 0.98]
0.9666666666666667


# Decision Tree

In [7]:
dtc = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
print(dtc)
print(np.average(dtc))

[0.98 0.94 1.  ]
0.9733333333333333


# Naive-Bayes GaussianNB

In [9]:
from sklearn.naive_bayes import GaussianNB

gauss = cross_val_score(GaussianNB(), iris.data, iris.target, cv=3)
print(gauss)
print(np.average(gauss))

[0.92 0.94 0.96]
0.94
