# Saving models using Joblib and pickle

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('d:/jupyter/datasets/homeprices.csv')

In [3]:
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = LinearRegression()

In [5]:
model.fit(df[['area']], df.price)

LinearRegression()

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

# Save model using Pickle

In [9]:
import pickle

In [10]:
with open('model_pickle', 'wb') as file:
    pickle.dump(model,file)

In [11]:
with open('model_pickle', 'rb') as file:
    pickle.load(file)

In [12]:
model.predict([[5000]])

array([859554.79452055])

# Save model Using Joblib 

In [15]:
import joblib
joblib.dump(model, 'model_joblib')


['model_joblib']

In [17]:
mj = joblib.load('model_joblib')
mj.coef_

array([135.78767123])