In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [29]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [30]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [31]:
len(x_train), len(x_test)

(1257, 540)

In [32]:
lr = LogisticRegression(solver='sag', max_iter=1000)  # 0.9629629629629629
# lr = LogisticRegression(solver='newton-cg', max_iter=100)  # 0.9574074074074074
lr.fit(x_train, y_train)
lr.score(x_test, y_test)  # 0.9703703703703703


0.9555555555555556

In [33]:
sv = SVC()
sv.fit(x_train,y_train)
sv.score(x_test, y_test)  # 0.987037037037037


0.9925925925925926

In [34]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)  # 0.9722222222222222


0.9777777777777777

In [35]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [36]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [37]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [38]:
get_score(lr,x_train, x_test, y_train, y_test)

0.9555555555555556

In [39]:
get_score(sv, x_train, x_test, y_train, y_test)


0.9925925925925926

In [40]:
get_score(rf, x_train, x_test, y_train, y_test)


0.9722222222222222

In [41]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)

In [42]:
scores_lr = []
scores_sv = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    scores_lr.append(get_score(lr, x_train, x_test, y_train, y_test))
    scores_sv.append(get_score(sv, x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(rf, x_train, x_test, y_train, y_test))


    
                            


In [43]:
scores_lr

[0.9248747913188647, 0.9415692821368948, 0.9115191986644408]

In [44]:
scores_sv

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [45]:
scores_rf

[0.9248747913188647, 0.9432387312186978, 0.9198664440734557]

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
cross_val_score(LogisticRegression(solver='sag', max_iter=1000), digits.data, digits.target, cv=3)

array([0.92153589, 0.94156928, 0.91652755])

In [48]:
cross_val_score(sv, digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [49]:
cross_val_score(rf, digits.data, digits.target, cv=3)

array([0.92153589, 0.95993322, 0.92487479])

# parameter tuning

In [50]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=3)
np.average(scores1)


0.8903728436282693

In [51]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=3)
np.average(scores2)

0.9226488592097941

In [52]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=3)
np.average(scores3)


0.9371174179187535

In [53]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target, cv=3)
np.average(scores4)


0.9337785197551475